# Generated by Django 2.2.1 on 2020-06-18 21:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=40)),
                ('Last_name', models.CharField(max_length=40)),
                ('Email', models.EmailField(default=False, max_length=70, unique=True)),
                ('phone_Number', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(regex='^(0|\\+)\\d{8,15}$')])),
                ('Occupation', models.CharField(default=False, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_name', models.CharField(max_length=30)),
                ('Subject_code', models.IntegerField()),
                ('Subject_teacher', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tsc_no', models.TextField(max_length=50)),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Email', models.EmailField(default=True, max_length=254, unique=True)),
                ('Phone_Number', models.CharField(default=False, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(regex='^(0|\\+)\\d{8,15}$')])),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHS_app.Subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_form', models.IntegerField(auto_created=True)),
                ('DateOfBirth', models.DateTimeField(auto_created=True, default=False)),
                ('Adm_no', models.IntegerField(unique=True)),
                ('First_name', models.CharField(max_length=40)),
                ('Last_name', models.CharField(max_length=40)),
                ('Surname', models.CharField(max_length=40)),
                ('Former_school', models.CharField(default=False, max_length=70)),
                ('KCPE_Marks', models.IntegerField(default=True)),
                ('Admittedon', models.DateTimeField(auto_now_add=True)),
                ('Cleared', models.BooleanField(default=False)),
                ('Subjects_taken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHS_app.Subjects')),
                ('parents_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHS_app.Parents')),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admittedon', models.DateTimeField(auto_now_add=True)),
                ('Cleared', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHS_app.Student')),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHS_app.Subjects')),
            ],
        ),
    ]
