# Generated by Django 2.2.1 on 2020-08-12 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CHS_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='subjects',
            new_name='Subjects',
        ),
    ]
