# Generated by Django 2.2.1 on 2020-09-16 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CHS_app', '0003_event_fee_hostel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parents',
            old_name='First_name',
            new_name='Parents_name',
        ),
        migrations.RemoveField(
            model_name='parents',
            name='Last_name',
        ),
    ]
