# Generated by Django 2.2.1 on 2020-09-21 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CHS_app', '0004_auto_20200916_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parents_name',
        ),
    ]
