# Generated by Django 2.2.1 on 2020-09-21 09:11

import CHS_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHS_app', '0005_remove_student_parents_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Subjects_taken',
            field=models.IntegerField(default=True, verbose_name=CHS_app.models.Subjects),
        ),
    ]
