# Generated by Django 2.2.1 on 2020-09-21 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CHS_app', '0006_auto_20200921_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='Subjects',
        ),
    ]
