# Generated by Django 2.2.1 on 2020-09-22 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CHS_app', '0007_remove_teachers_subjects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admission',
        ),
    ]
